keypress_delay_ms: 50
modmap:
  - name: Caps -> Esc
    remap:
      CapsLock: Esc
  - name: Esc -> Caps
    remap:
      Esc: CapsLock
#   - name: A/D Shortcuts
#     remap:
#       SHIFT_R:
#         alone:
#           set_mode: ad
keymap:
  - name: Default
    # keypress_delay_ms: 25
    exact_match: true
    remap:
      M-a: C-a
      M-x: C-x
      M-Shift-c: C-Shift-c
      M-Shift-v: C-Shift-v
      M-n: C-n
      M-t: C-t
      M-p: C-p
      M-Shift-n: C-Shift-n
      M-Shift-t: C-Shift-t
      M-Shift-p: C-Shift-p
      M-w: C-w
      M-r: C-r
      M-f: C-f
      M-s: C-s
      M-l: C-l
      Super-M-i: F12
      M-KEY_0: C-KEY_0
      M-Shift-KEY_MINUS: C-Shift-KEY_MINUS
      M-KEY_MINUS: C-KEY_MINUS
      M-Shift-KEY_EQUAL: C-Shift-KEY_EQUAL
      M-KEY_EQUAL: C-KEY_EQUAL
      Super-backspace: C-backspace
      Super-delete: C-delete
      M-backspace: [Shift-home, backspace]
      M-delete: [Shift-end, delete]
      Super-left: C-left
      Super-right: C-right
      M-z: C-z
      M-y: C-y
      M-Shift-z: C-Shift-z
      Super_R-3: Shift-3
      M-BTN_LEFT: C-BTN_LEFT
      M-BTN_TOUCH: C-BTN_LEFT
  - name: Except Firefox
    application:
      not: firefox
    remap:
      M-left: home
      M-right: end
  - name: Kitty
    application:
      only: kitty
    remap:
      M-c: C-Shift-c
      M-v: C-Shift-v
  - name: Except Kitty
    application:
      not: kitty
    remap:
      M-c: C-c
      M-v: C-v
  # - name: A/D Shortcuts
  #   remap:
  #     Esc:
  #       set_mode: default
  #     d:
  #       launch: ["bash", "-c", "echo TODO 'docker compose up -d --build\n'"]
  #       set_mode: default
  #   mode: ad
