#!/bin/sh

PLUGIN_DIR="~/.config/sketchybar/plugins"

sketchybar --bar \
   height=37 \
   color=0x80666666 \
   blur_radius=32

sketchybar --default \
    icon.font="FiraCode Nerd Font Mono" \
    label.font="FiraCode Nerd Font Mono" \
    icon.font.size="20.0" \
    label.font.size="12.0" \
    icon.padding_left=8 \
    label.padding_left=8 \
    label.padding_right=8 \
    background.padding_left=8 \
    background.height=28 \
    background.color=0x80000000 \
    background.corner_radius=8

# left side
SPACE_ICONS=("Safari" "Telegram" "Terminal" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"
do
    sid=$(($i+1))
    sketchybar --add space space.$sid left --set space.$sid \
        associated_space=$sid \
        label=${SPACE_ICONS[i]} \
        icon.drawing=off \
        background.color=0x20000000 \
        script="$PLUGIN_DIR/space.sh" \
        click_script="yabai -m space --focus $sid"
    done

# right side
sketchybar --add item clock right --set clock \
    update_freq=1 \
    icon="" \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right --set battery \
    update_freq=1 \
    script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change

sketchybar --add item wifi right --set wifi \
    script="$PLUGIN_DIR/wifi.sh" \
    --subscribe wifi wifi_change
    '
